### ISSUE TITLE
ref and alt columns are in the wrong spots

### ISSUE THREAD

**Issue by roblanf** [W-L/ProblematicSites_SARS-CoV2#1]
A heads up that your data are in the wrong columns for REF and ALT in the VCF here: https://raw.githubusercontent.com/W-L/ProblematicSites_SARS-CoV2/master/problematic_sites_sarsCov2.vcf. 

Specifically, the REF is in the ALT column, and the ALT is in the QUAL column.

Rob

**Comment by W-L** [comment]
Hi Rob, 
thanks for the heads up. The columns might not look aligned in the raw text file, but they are in their correct places. `#CHROM` is the header of the first column despite the `#`-prefix (following vcf-format specification).
Best wishes,
Lukas

**Comment by roblanf** [comment]
Oh right, got it! Thanks for explaining (and refraining to call me a complete idiot).

Rob
