### ISSUE TITLE
File names with colon in archived_vcf break cloning on Windows

### ISSUE THREAD

**Issue by KatSteinke** [W-L/ProblematicSites_SARS-CoV2#10]
I'm hoping to use this repository in a pipeline I'm working on - it'll run on an Ubuntu machine, but unfortunately, I have to do all my development work on a Windows machine. On Windows, however, I can't clone the repository because of the way the files in archived_vcf are named - the names with colons (e.g. "problematic_sites_sarsCov2.2020-07-14-13:59.vcf") make it throw up  `invalid path`. Would it be possible to rename these files, for example replacing the colon by a period (so for example  "problematic_sites_sarsCov2.2020-07-14-13.59.vcf")?

**Comment by W-L** [comment]
That's an unfortunate issue! In case there are other pipelines that rely on the current naming scheme, we decided to create a new branch of the repository where the colons are replaced by dashes. You can clone that branch with:
`git clone --single-branch --branch nocolon https://github.com/W-L/ProblematicSites_SARS-CoV2.git`
Please let me know if windows keeps complaining!

**Comment by KatSteinke** [comment]
Worked like a charm, thanks!
