### ISSUE TITLE
File "mask_alignment_using_vcf.py" - Python KeyError Exceptions

### ISSUE THREAD

**Issue by AnyaKovalenko** [W-L/ProblematicSites_SARS-CoV2#14]
Hello. Please could you help me. After using the following command: 
`python mask_alignment_using_vcf.py -i input_msa.fasta -o output_masked_msa.fasta -v problematic_sites_sarsCov2.vcf`

I received a Python traceback with a KeyError. See the message below: 
```
Traceback (most recent call last):
  File "mask_alignment_using_vcf.py", line 174, in <module>
    main()
  File "mask_alignment_using_vcf.py", line 156, in main
    iffy_alignment_sites = [ref_coord_dic[int(i)-1] for i in iffy_sites]
  File "mask_alignment_using_vcf.py", line 156, in <listcomp>
    iffy_alignment_sites = [ref_coord_dic[int(i)-1] for i in iffy_sites]
KeyError: 29815
```

Please could you help to resolve it and understand the reasons why it get raised. Many thanks in advance. And thank you for creating this very useful tool.

**Comment by W-L** [comment]
Hi,
Thanks for your message. I suspect that the reference sequence you are using is shorter than what the script is expecting. The last sites suggested for masking are 29804:29903, i.e. the end of the reference sequence. We built this resource around the reference accession MN908947 with length 29903, whereas your reference seems to be slightly shorter. What did you specify as reference?
Hope this helps!

**Comment by AnyaKovalenko** [comment]
Hi @W-L thank you so much for your response. It helped, just chose the correct size of the ref genome.
