### ISSUE TITLE
Citation?

### ISSUE THREAD

**Issue by cmkobel** [W-L/ProblematicSites_SARS-CoV2#6]
Hello

How do I reference the list of problematic sites in a paper pending peer review?

Is there a published paper that shows how the sites have been recognized and classified?

Kind regards, Carl

**Comment by NicolaDM** [comment]
Hi Carl,

Yes, you can cite these sources:

https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1009175

https://virological.org/t/issues-with-sars-cov-2-sequencing-data/473
